################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/at.c \
C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/command.c \
C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/debug.c \
C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/hw_gpio.c \
C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/hw_rtc.c \
C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/hw_spi.c \
C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/lora.c \
C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/main.c \
../Application/User/Src/stm32l0xx_hal_msp.c \
../Application/User/Src/stm32l0xx_hw.c \
../Application/User/Src/stm32l0xx_it.c \
C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/test_rf.c \
../Application/User/Src/tiny_sscanf.c \
../Application/User/Src/tiny_vsnprintf.c \
C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/vcom.c 

OBJS += \
./Application/User/Src/at.o \
./Application/User/Src/command.o \
./Application/User/Src/debug.o \
./Application/User/Src/hw_gpio.o \
./Application/User/Src/hw_rtc.o \
./Application/User/Src/hw_spi.o \
./Application/User/Src/lora.o \
./Application/User/Src/main.o \
./Application/User/Src/stm32l0xx_hal_msp.o \
./Application/User/Src/stm32l0xx_hw.o \
./Application/User/Src/stm32l0xx_it.o \
./Application/User/Src/test_rf.o \
./Application/User/Src/tiny_sscanf.o \
./Application/User/Src/tiny_vsnprintf.o \
./Application/User/Src/vcom.o 

C_DEPS += \
./Application/User/Src/at.d \
./Application/User/Src/command.d \
./Application/User/Src/debug.d \
./Application/User/Src/hw_gpio.d \
./Application/User/Src/hw_rtc.d \
./Application/User/Src/hw_spi.d \
./Application/User/Src/lora.d \
./Application/User/Src/main.d \
./Application/User/Src/stm32l0xx_hal_msp.d \
./Application/User/Src/stm32l0xx_hw.d \
./Application/User/Src/stm32l0xx_it.d \
./Application/User/Src/test_rf.d \
./Application/User/Src/tiny_sscanf.d \
./Application/User/Src/tiny_vsnprintf.d \
./Application/User/Src/vcom.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/Src/at.o: C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/at.c Application/User/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -I../Application/User/Inc -I../Middlewares/LoRa/Phy -I../Middlewares/LoRa/Utilities -I../Middlewares/LoRa/Crypto -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Core/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Include" -I../Drivers/STM32L0xx_HAL_Driver/Inc -I../Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Middlewares" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Application/User/Src/at.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/Src/command.o: C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/command.c Application/User/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -I../Application/User/Inc -I../Middlewares/LoRa/Phy -I../Middlewares/LoRa/Utilities -I../Middlewares/LoRa/Crypto -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Core/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Include" -I../Drivers/STM32L0xx_HAL_Driver/Inc -I../Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Middlewares" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Application/User/Src/command.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/Src/debug.o: C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/debug.c Application/User/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -I../Application/User/Inc -I../Middlewares/LoRa/Phy -I../Middlewares/LoRa/Utilities -I../Middlewares/LoRa/Crypto -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Core/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Include" -I../Drivers/STM32L0xx_HAL_Driver/Inc -I../Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Middlewares" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Application/User/Src/debug.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/Src/hw_gpio.o: C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/hw_gpio.c Application/User/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -I../Application/User/Inc -I../Middlewares/LoRa/Phy -I../Middlewares/LoRa/Utilities -I../Middlewares/LoRa/Crypto -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Core/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Include" -I../Drivers/STM32L0xx_HAL_Driver/Inc -I../Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Middlewares" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Application/User/Src/hw_gpio.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/Src/hw_rtc.o: C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/hw_rtc.c Application/User/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -I../Application/User/Inc -I../Middlewares/LoRa/Phy -I../Middlewares/LoRa/Utilities -I../Middlewares/LoRa/Crypto -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Core/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Include" -I../Drivers/STM32L0xx_HAL_Driver/Inc -I../Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Middlewares" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Application/User/Src/hw_rtc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/Src/hw_spi.o: C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/hw_spi.c Application/User/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -I../Application/User/Inc -I../Middlewares/LoRa/Phy -I../Middlewares/LoRa/Utilities -I../Middlewares/LoRa/Crypto -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Core/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Include" -I../Drivers/STM32L0xx_HAL_Driver/Inc -I../Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Middlewares" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Application/User/Src/hw_spi.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/Src/lora.o: C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/lora.c Application/User/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -I../Application/User/Inc -I../Middlewares/LoRa/Phy -I../Middlewares/LoRa/Utilities -I../Middlewares/LoRa/Crypto -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Core/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Include" -I../Drivers/STM32L0xx_HAL_Driver/Inc -I../Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Middlewares" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Application/User/Src/lora.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/Src/main.o: C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/main.c Application/User/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -I../Application/User/Inc -I../Middlewares/LoRa/Phy -I../Middlewares/LoRa/Utilities -I../Middlewares/LoRa/Crypto -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Core/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Include" -I../Drivers/STM32L0xx_HAL_Driver/Inc -I../Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Middlewares" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Application/User/Src/main.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/Src/%.o Application/User/Src/%.su Application/User/Src/%.cyclo: ../Application/User/Src/%.c Application/User/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -I../Application/User/Inc -I../Middlewares/LoRa/Phy -I../Middlewares/LoRa/Utilities -I../Middlewares/LoRa/Crypto -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Core/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Include" -I../Drivers/STM32L0xx_HAL_Driver/Inc -I../Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Middlewares" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/Src/test_rf.o: C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/test_rf.c Application/User/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -I../Application/User/Inc -I../Middlewares/LoRa/Phy -I../Middlewares/LoRa/Utilities -I../Middlewares/LoRa/Crypto -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Core/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Include" -I../Drivers/STM32L0xx_HAL_Driver/Inc -I../Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Middlewares" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Application/User/Src/test_rf.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/Src/vcom.o: C:/Users/Wagne/OneDrive/Programmierungen/LORA\ P2P/LT-22222-L/Projects/Multi/Applications/LoRa/DRAGINO-LRWAN(AT)/src/vcom.c Application/User/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -I../Application/User/Inc -I../Middlewares/LoRa/Phy -I../Middlewares/LoRa/Utilities -I../Middlewares/LoRa/Crypto -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Core/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Drivers/CMSIS/Include" -I../Drivers/STM32L0xx_HAL_Driver/Inc -I../Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/Wagne/OneDrive/Programmierungen/LORA P2P/LT-22222-L/workspace_lora/LoRa_P2P_Enhanced/Middlewares" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Application/User/Src/vcom.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-Application-2f-User-2f-Src

clean-Application-2f-User-2f-Src:
	-$(RM) ./Application/User/Src/at.cyclo ./Application/User/Src/at.d ./Application/User/Src/at.o ./Application/User/Src/at.su ./Application/User/Src/command.cyclo ./Application/User/Src/command.d ./Application/User/Src/command.o ./Application/User/Src/command.su ./Application/User/Src/debug.cyclo ./Application/User/Src/debug.d ./Application/User/Src/debug.o ./Application/User/Src/debug.su ./Application/User/Src/hw_gpio.cyclo ./Application/User/Src/hw_gpio.d ./Application/User/Src/hw_gpio.o ./Application/User/Src/hw_gpio.su ./Application/User/Src/hw_rtc.cyclo ./Application/User/Src/hw_rtc.d ./Application/User/Src/hw_rtc.o ./Application/User/Src/hw_rtc.su ./Application/User/Src/hw_spi.cyclo ./Application/User/Src/hw_spi.d ./Application/User/Src/hw_spi.o ./Application/User/Src/hw_spi.su ./Application/User/Src/lora.cyclo ./Application/User/Src/lora.d ./Application/User/Src/lora.o ./Application/User/Src/lora.su ./Application/User/Src/main.cyclo ./Application/User/Src/main.d ./Application/User/Src/main.o ./Application/User/Src/main.su ./Application/User/Src/stm32l0xx_hal_msp.cyclo ./Application/User/Src/stm32l0xx_hal_msp.d ./Application/User/Src/stm32l0xx_hal_msp.o ./Application/User/Src/stm32l0xx_hal_msp.su ./Application/User/Src/stm32l0xx_hw.cyclo ./Application/User/Src/stm32l0xx_hw.d ./Application/User/Src/stm32l0xx_hw.o ./Application/User/Src/stm32l0xx_hw.su ./Application/User/Src/stm32l0xx_it.cyclo ./Application/User/Src/stm32l0xx_it.d ./Application/User/Src/stm32l0xx_it.o ./Application/User/Src/stm32l0xx_it.su ./Application/User/Src/test_rf.cyclo ./Application/User/Src/test_rf.d ./Application/User/Src/test_rf.o ./Application/User/Src/test_rf.su ./Application/User/Src/tiny_sscanf.cyclo ./Application/User/Src/tiny_sscanf.d ./Application/User/Src/tiny_sscanf.o ./Application/User/Src/tiny_sscanf.su ./Application/User/Src/tiny_vsnprintf.cyclo ./Application/User/Src/tiny_vsnprintf.d ./Application/User/Src/tiny_vsnprintf.o ./Application/User/Src/tiny_vsnprintf.su ./Application/User/Src/vcom.cyclo ./Application/User/Src/vcom.d ./Application/User/Src/vcom.o ./Application/User/Src/vcom.su

.PHONY: clean-Application-2f-User-2f-Src

